id: b6eb7225-30b8-4926-86bf-2108b6098d6e
type: application
interactions:
- targetId: 8cb7468e-e6ed-4647-824b-7e6634b24fd9
  type: service
  level: component
- targetId: 707f9ecc-25db-48db-b7de-19087702a1bd
  type: domain
  level: component
annotations:
- namespace: c4modeler
  name: position
  value:
    ed347376-4a72-474c-9034-e64ba4c6736b:
      x: 140
      y: 124.5
name: NewApplication
description: Description for NewApplication
baseApiUrl: ca/baseapi
